### ISSUE TITLE
0 value is not encoded correctly

### ISSUE THREAD

**Issue by terashi58** [sunmyinf/godate#35]
When I encode a 0-value Date into JSON, the encoded string get to be "-0001-11-30".
It looks weird. And it cannot be decoded as the original 0-value.

It's not so clear how it should be represented, but at least, it is expected encoding/decoding don't change the value.

If there is no good representation of the 0-value Date, what about handling such a case as an error, and suggesting to use NullDate?

**Comment by terashi58** [comment]
Or, we may be able to encode it as "null".

**Comment by sunmyinf** [comment]
Thanks! I think zero date to be encoded "null" makes sense, too.
